version: '3.3'
services:
  api:
    image: node:alpine
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start:dev
    environment:
      - NODE_ENV=development
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
       - meal_planner_pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    meal_planner_pg_data: