version: '3.3'
services:
  api:
    image: node:12
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
      - /node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
    depends_on:
      - postgres
    links:
      - 'postgres:postgres'

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
       - meal_planner_pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    meal_planner_pg_data: